params:
  profileMode:
    enabled: true
    title: "Morgan Nettles" # optional default will be site title
    subtitle: "Writer, developer, tinkerer"
    imageUrl: "<image link>" # optional
    imageTitle: "<title of image as alt>" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      # - name: Archive
      #   url: "/archive"
      - name: Projects
        url: "/content/projects.md"
      #- name: Github
      #url: "https://github.com/monett010"

  socialIcons: # optional
    - name: "LinkedIn"
      url: "https://linkedin.com/#"
    - name: "Github"
      url: "https://github.com/mnettl"
