params:
  defaultTheme: dark
  disableThemeToggle: true
  profileMode:
    enabled: true
    title: "Morgan Nettles" # optional default will be site title
    subtitle: "Writer, developer, tinkerer"
    # imageUrl: "<image link>" # optional
    # imageTitle: "<title of image as alt>" # optional
    # imageWidth: 120 # custom size
    # imageHeight: 120 # custom size
    buttons:
      # - name: Archive
      #   url: "/archive"
      - name: Projects
        url: "/projects"
      #- name: Github
      #url: "https://github.com/monett010"
      - name: Technical Writing
        url: "/tech_writing"

  socialIcons: # optional
    # - name: "LinkedIn"
    #   url: "https://linkedin.com/#"
    - name: "Github"
      url: "https://github.com/mnettl"
